package TicTacToe_twoplayer;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zebra
 */
public class TicTacToe extends javax.swing.JFrame {

    private String startGame = "X";
    private int xCount = 0;
    private int oCount = 0;

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(620, 360);
    }

    private void gameScore() {
        jlbPlayerX.setText(String.valueOf(xCount));
        jlbPlayerO.setText(String.valueOf(oCount));
    }

    private void choose_a_Player() {
        if (startGame.equalsIgnoreCase("X")) {
            startGame = "O";
        } else {
            startGame = "X";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_header = new javax.swing.JPanel();
        title_header = new javax.swing.JLabel();
        back_btn = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        playerX = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlbPlayerX = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        playerO = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jlbPlayerO = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btn8 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btn9 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");

        bg_header.setBackground(new java.awt.Color(85, 222, 226));
        bg_header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bg_header.setLayout(new java.awt.BorderLayout());

        title_header.setFont(new java.awt.Font("Ubuntu", 1, 92)); // NOI18N
        title_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_header.setText("Tic Tac Toe");
        bg_header.add(title_header, java.awt.BorderLayout.PAGE_START);

        back_btn.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jPanel1.setLayout(new java.awt.BorderLayout());

        btn1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btn2.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        btn3.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn3, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        playerX.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        playerX.setText("Player X :");
        jPanel4.add(playerX, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jlbPlayerX.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jPanel5.add(jlbPlayerX, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        btn4.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel6.add(btn4, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        btn5.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel7.add(btn5, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        btn6.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel8.add(btn6, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        playerO.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        playerO.setText("Player O :");
        playerO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(playerO, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jlbPlayerO.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jPanel10.add(jlbPlayerO, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        btn7.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel11.add(btn7, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        btn8.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel12.add(btn8, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel12);

        jPanel13.setLayout(new java.awt.BorderLayout());

        btn9.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel13.add(btn9, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel14.add(btnReset, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel15.add(btnExit, java.awt.BorderLayout.CENTER);

        back_btn.add(jPanel15);

        bg_header.add(back_btn, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg_header, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JFrame frame;//Khai bao frame
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

        btn1.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn1.setForeground(Color.GREEN);
        } else {
            btn1.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn1ActionPerformed

    private void winningGame() {
        String b1 = btn1.getText();
        String b2 = btn2.getText();
        String b3 = btn3.getText();

        String b4 = btn4.getText();
        String b5 = btn5.getText();
        String b6 = btn6.getText();

        String b7 = btn7.getText();
        String b8 = btn8.getText();
        String b9 = btn9.getText();

        //hang ngang x
        if (b1 == ("X") && b2 == ("X") && b3 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn1.setBackground(Color.YELLOW);
            btn2.setBackground(Color.YELLOW);
            btn3.setBackground(Color.YELLOW);
        } else if (b4 == ("X") && b5 == ("X") && b6 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn4.setBackground(Color.YELLOW);
            btn5.setBackground(Color.YELLOW);
            btn6.setBackground(Color.YELLOW);
        } else if (b7 == ("X") && b8 == ("X") && b9 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn7.setBackground(Color.YELLOW);
            btn8.setBackground(Color.YELLOW);
            btn9.setBackground(Color.YELLOW);
        }// hang cheo x
        else if (b1 == ("X") && b5 == ("X") && b9 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn1.setBackground(Color.CYAN);
            btn5.setBackground(Color.CYAN);
            btn9.setBackground(Color.CYAN);
        } else if (b3 == ("X") && b5 == ("X") && b7 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn3.setBackground(Color.CYAN);
            btn5.setBackground(Color.CYAN);
            btn7.setBackground(Color.CYAN);
        }//hang doc  x
        else if (b1 == ("X") && b4 == ("X") && b7 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn1.setBackground(Color.ORANGE);
            btn4.setBackground(Color.ORANGE);
            btn7.setBackground(Color.ORANGE);
        } else if (b2 == ("X") && b5 == ("X") && b8 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn2.setBackground(Color.ORANGE);
            btn5.setBackground(Color.ORANGE);
            btn8.setBackground(Color.ORANGE);
        } else if (b3 == ("X") && b6 == ("X") && b9 == ("X")) {
            JOptionPane.showMessageDialog(this, "Player X wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
            btn3.setBackground(Color.ORANGE);
            btn6.setBackground(Color.ORANGE);
            btn9.setBackground(Color.ORANGE);
        } //end X
        //hang ngang o
        else if (b1 == ("O") && b2 == ("O") && b3 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn1.setBackground(Color.YELLOW);
            btn2.setBackground(Color.YELLOW);
            btn3.setBackground(Color.YELLOW);
        } else if (b4 == ("O") && b5 == ("O") && b6 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn4.setBackground(Color.YELLOW);
            btn5.setBackground(Color.YELLOW);
            btn6.setBackground(Color.YELLOW);
        } else if (b7 == ("O") && b8 == ("O") && b9 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn7.setBackground(Color.YELLOW);
            btn8.setBackground(Color.YELLOW);
            btn9.setBackground(Color.YELLOW);
        }// hang cheo O
        else if (b1 == ("O") && b5 == ("O") && b9 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn1.setBackground(Color.CYAN);
            btn5.setBackground(Color.CYAN);
            btn9.setBackground(Color.CYAN);
        } else if (b3 == ("O") && b5 == ("O") && b7 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn3.setBackground(Color.CYAN);
            btn5.setBackground(Color.CYAN);
            btn7.setBackground(Color.CYAN);
        }//hang doc  O
        else if (b1 == ("O") && b4 == ("O") && b7 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn1.setBackground(Color.ORANGE);
            btn4.setBackground(Color.ORANGE);
            btn7.setBackground(Color.ORANGE);
        } else if (b2 == ("O") && b5 == ("O") && b8 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn2.setBackground(Color.ORANGE);
            btn5.setBackground(Color.ORANGE);
            btn8.setBackground(Color.ORANGE);
        } else if (b3 == ("O") && b6 == ("O") && b9 == ("O")) {
            JOptionPane.showMessageDialog(this, "Player O wins", "Messager",
                    JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
            btn3.setBackground(Color.ORANGE);
            btn6.setBackground(Color.ORANGE);
            btn9.setBackground(Color.ORANGE);
        }

    }
   
    public void resetGame() {
        btn1.setText(null);
        btn2.setText(null);
        btn3.setText(null);

        btn4.setText(null);
        btn5.setText(null);
        btn6.setText(null);

        btn7.setText(null);
        btn8.setText(null);
        btn9.setText(null);

        btn1.setBackground(null);
        btn2.setBackground(null);
        btn3.setBackground(null);

        btn4.setBackground(null);
        btn5.setBackground(null);
        btn6.setBackground(null);

        btn7.setBackground(null);
        btn8.setBackground(null);
        btn9.setBackground(null);

    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "You want to exit?", "Messager",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
        //
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        btn2.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn2.setForeground(Color.GREEN);
        } else {
            btn2.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        btn3.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn3.setForeground(Color.GREEN);
        } else {
            btn3.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        btn4.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn4.setForeground(Color.GREEN);
        } else {
            btn4.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        btn5.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn5.setForeground(Color.GREEN);
        } else {
            btn5.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        btn6.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn6.setForeground(Color.GREEN);
        } else {
            btn6.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        btn7.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn7.setForeground(Color.GREEN);
        } else {
            btn7.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        btn8.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn8.setForeground(Color.GREEN);
        } else {
            btn8.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        btn9.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            btn9.setForeground(Color.GREEN);
        } else {
            btn9.setForeground(Color.BLUE);
        }
        choose_a_Player();
        winningGame();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetGame();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel back_btn;
    private javax.swing.JPanel bg_header;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jlbPlayerO;
    private javax.swing.JButton jlbPlayerX;
    private javax.swing.JButton playerO;
    private javax.swing.JButton playerX;
    private javax.swing.JLabel title_header;
    // End of variables declaration//GEN-END:variables
}
